# Generated by Django 4.0 on 2022-02-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='account_summ',
            field=models.IntegerField(),
        ),
    ]
